# Dockerfile
FROM python:3.12-slim

# 必要なパッケージをaptでインストール（curl など）
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      curl \
      ca-certificates \
      xmlstarlet \
      gettext-base \
    && rm -rf /var/lib/apt/lists/*


# AWS CLI & boto3 を pip でインストール
RUN pip install --no-cache-dir awscli

